export const projects = [
  {
    id: 'ac-bracket',
    title: 'MGB AC Bracket',
    accent: '#1a3a5c',
    summary: 'AC mounting bracket for the 1972 MGB — 10+ printed prototypes before metal fabrication.',
    cad: {
      description: 'Modified AC mounting bracket for improved fitment in the MGB engine bay — iterated through multiple versions.',
      longDescription:
        'The AC bracket went through at least ten printed iterations (revisions 6–10 are on record) before reaching a final fitment. Each version addressed specific clearance issues discovered when test-fitting against the engine block, accessory drive, and adjacent components.',
      tags: ['FreeCAD', 'Mechanical', 'MGB'],
      model: '/models/ac-bracket-combined.stl',
      modelRotation: [0, 0, Math.PI / 2],
      specs: {
        'Tool': 'FreeCAD',
        'Iterations': '10+',
        'Final Material': 'Metal (fabricated)',
        'Prototype Material': 'PLA',
        'Car': '1972 MGB',
      },
      process: [
        'Started with rough measurements of the AC compressor mounting face and engine bay clearances.',
        'Printed each revision in PLA on the Ender 3 V3 SE to test fit before committing to metal.',
        'Revised clearance geometry through revisions 6–10 to clear the adjacent drive belt path.',
        'Final design handed off for metal fabrication.',
      ],
      images: [],
      gallery: [
        { type: 'model', src: '/models/ac-bracket-rev2v4.stl', label: 'Revision 2 v4' },
        { type: 'model', src: '/models/ac-bracket-rev3.stl', label: 'Revision 3' },
        { type: 'model', src: '/models/ac-bracket-rev4.stl', label: 'Revision 4' },
        { type: 'model', src: '/models/ac-bracket-rev5.stl', label: 'Revision 5' },
        { type: 'model', src: '/models/ac-bracket-rev9.stl', label: 'Revision 9' },
        { type: 'model', src: '/models/ac-bracket.stl', label: 'Revision 6 — Modified v2' },
      ],
    },
    printing: {
      description: 'Printed and test-fit AC bracket revisions 6 through 10 on the Ender 3 V3 SE, iterating until correct clearance was achieved.',
      longDescription:
        'The AC bracket required the most print iterations of any MGB part — at least 10 revisions. Each printed version was physically installed in the engine bay to check clearances against the belt path, water pump, and adjacent hardware before the next design change was made.',
      tags: ['PLA', 'Own Design', 'Ender 3 V3 SE', 'MGB'],
      model: '/models/ac-bracket-combined.stl',
      modelRotation: [0, 0, Math.PI / 2],
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Slicer': 'Cura / OrcaSlicer',
        'Material': 'PLA',
        'Revisions printed': '10+',
        'Design': 'FreeCAD (own)',
      },
      process: [
        'Early revisions (1–5) established the basic bolt pattern and compressor mounting face.',
        'Revisions 6–10 focused on clearance geometry — each printed, installed, and measured before the next change.',
        'Final printed version was used as a template for metal fabrication.',
        'The PLA prototype confirmed that all bolt holes lined up and the belt path was clear before cutting metal.',
      ],
      images: [],
      gallery: [
        { type: 'model', src: '/models/ac-bracket-rev2v4.stl', label: 'Revision 2 v4' },
        { type: 'model', src: '/models/ac-bracket-rev3.stl', label: 'Revision 3' },
        { type: 'model', src: '/models/ac-bracket-rev4.stl', label: 'Revision 4' },
        { type: 'model', src: '/models/ac-bracket-rev5.stl', label: 'Revision 5' },
        { type: 'model', src: '/models/ac-bracket-rev9.stl', label: 'Revision 9' },
        { type: 'model', src: '/models/ac-bracket.stl', label: 'Revision 6 — Modified v2' },
      ],
    },
    metalwork: {
      description: 'Metal version of the CAD-designed AC bracket — fabricated and fitted to the MGB engine bay.',
      longDescription:
        'After 10+ printed PLA prototypes confirmed the geometry, the AC bracket was fabricated in metal. The printed prototype served as the direct template, ensuring the metal version fit correctly on the first attempt.',
      tags: ['Metalwork', 'MGB', 'AC'],
      specs: {
        'Material': 'TBD',
        'Template': 'PLA prototype (10+ revisions)',
        'Car': '1972 MGB',
      },
      process: [
        'Final PLA print used as the direct template for cutting and bending.',
        'Bolt holes transferred from the printed template.',
      ],
      images: [],
    },
  },
  {
    id: 'overflow-bottle',
    title: 'Overflow Bottle',
    accent: '#2a4a6a',
    summary: 'Custom coolant overflow bottle for the MGB — 5 FreeCAD iterations to fit the engine bay, printed in PLA.',
    cad: {
      cameraPull: 2,
      description: 'Custom coolant overflow bottle designed through 5 FreeCAD iterations to fit cleanly in the MGB engine bay.',
      longDescription:
        'The MGB engine bay has limited space, so a purpose-built coolant overflow bottle was designed in FreeCAD to use available space efficiently. Five revisions refined the bottle volume, cap thread geometry, and the bracket interface that holds it in place.',
      tags: ['FreeCAD', 'Fluid Systems', 'MGB'],
      model: '/models/overflow-bottle.stl',
      specs: {
        'Tool': 'FreeCAD',
        'Revisions': '5 (OverflowBottle through OverflowBottle5)',
        'Prototype Material': 'PLA',
        'Car': '1972 MGB',
      },
      process: [
        'Measured available envelope in the engine bay and identified the target mounting location.',
        'First version established the basic form; subsequent revisions refined the cap thread, filler neck angle, and bracket tabs.',
        'Printed each iteration in PLA to verify fit and coolant line routing before finalizing geometry.',
        'Support geometry in the final print was tuned for clean removal from the narrow internal passages.',
      ],
      images: [],
    },
    printing: {
      cameraPull: 2,
      description: 'Printed the FreeCAD-designed coolant overflow bottle on the Ender 3 V3 SE — support geometry tuned for clean removal.',
      longDescription:
        'After 5 FreeCAD design iterations, the overflow bottle was printed in PLA on the Ender 3 V3 SE. The print required custom support geometry for the internal filler neck passage, which was tuned to break away cleanly without damaging the bottle walls.',
      tags: ['PLA', 'Own Design', 'Ender 3 V3 SE', 'MGB'],
      model: '/models/overflow-bottle.stl',
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Slicer': 'OrcaSlicer',
        'Material': 'PLA',
        'Supports': 'Custom geometry',
        'Design': 'FreeCAD (own)',
      },
      process: [
        'Sliced in OrcaSlicer with custom support interface layers to prevent support bonding to the inner walls.',
        'Printed with 3 perimeters for wall strength and 20% gyroid infill.',
        'Support removal required care around the filler neck — refined support geometry in the final revision to make this easier.',
        'Test-fit in the engine bay confirmed correct clearance to the radiator hose and bracket tabs aligned.',
      ],
      images: [],
    },
  },
  {
    id: 'shift-knob',
    title: 'Custom Shift Knob',
    accent: '#3d2a5c',
    summary: 'Ergonomic shift knob for the MGB — curved geometry parametrically modeled in FreeCAD and printed in PLA.',
    cad: {
      cameraPull: 2,
      description: 'Curved shift knob with custom geometry, parametrically modeled and refined across multiple FreeCAD revisions.',
      longDescription:
        'A shift knob designed to fit the MGB gearbox shifter with custom ergonomic geometry. Multiple FreeCAD files track the design evolution — from the base knob shape through curved variants and fillet refinements — until a final printable form was achieved.',
      tags: ['FreeCAD', 'Ergonomic Design'],
      model: '/models/shift-knob.stl',
      specs: {
        'Tool': 'FreeCAD',
        'Design files': 'knob_custom, knob_custom_curved, knob_modify_1, knob_modify_2',
        'Material': 'PLA',
        'Layer height': '0.20 mm',
      },
      process: [
        'Started with a straight base knob (knob_custom.FCStd) to get the thread and diameter right.',
        'Added curved geometry in knob_custom_curved for a more ergonomic palm fit.',
        'Refined edge fillets and top surface curvature across knob_modify_1 and knob_modify_2.',
        'Printed and test-fit on the actual shifter between each major revision.',
      ],
      images: [],
    },
    printing: {
      cameraPull: 2,
      description: 'Printed the custom shift knob design in PLA; tested curved geometry and fit on the actual shifter.',
      longDescription:
        'The shift knob was printed in PLA across multiple revisions to validate the ergonomic shape and shifter thread fit. Printing at 0.20 mm layer height gave a good surface finish for a hand-contact part while keeping print time reasonable.',
      tags: ['PLA', 'Own Design', 'Ender 3 V3 SE'],
      model: '/models/shift-knob.stl',
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Slicer': 'OrcaSlicer',
        'Material': 'PLA',
        'Layer height': '0.20 mm',
        'Design': 'FreeCAD (own)',
      },
      process: [
        'First prints tested the internal thread diameter — adjusted model by 0.2 mm for a snug fit on the shifter.',
        'Printed at 0.20 mm layer height for surface quality on the curved top section.',
        'Hand-sanded the parting line after printing for a cleaner feel in use.',
      ],
      images: [],
    },
  },
  {
    id: 'washer-system',
    title: 'MGB Washer System',
    accent: '#2a5c4a',
    summary: 'Relocation bracket and adapter for the MGB washer pump — aftermarket components fitted to original mounting points.',
    cad: {
      description: 'Relocation bracket and adapter for the MGB washer pump — designed in FreeCAD to fit aftermarket components to original mounting points.',
      longDescription:
        'Two parts designed together as one system: a relocation bracket to move the washer pump to a new position in the engine bay, and a precision adapter to mate the aftermarket pump body to the original MGB mounting hole pattern. Both were parametrically modeled in FreeCAD so dimensions could be tuned without rebuilding sketches.',
      tags: ['FreeCAD', 'Mechanical', 'MGB'],
      model: '/models/washer-adapter.stl',
      specs: {
        'Tool': 'FreeCAD',
        'Parts': 'Relocation bracket + adapter',
        'Material': 'PLA prototype',
        'Layer height': '0.20 mm',
        'Car': '1972 MGB',
      },
      process: [
        'Measured existing pump body, mounting points on the engine block, and the aftermarket pump dimensions.',
        'Designed the relocation bracket parametrically to allow adjustment if mounting points shifted during the build.',
        'Designed the adapter to bridge the two mounting interfaces — original MGB hole pattern on one side, aftermarket pump on the other.',
        'Printed at 0.20 mm and validated thread engagement and hole spacing against both components.',
      ],
      images: [],
    },
    printing: {
      description: 'Printed the washer relocation bracket and adapter in PLA; validated thread engagement and mounting clearance on both components.',
      longDescription:
        'Both parts of the washer system — the relocation bracket and the adapter — were printed in PLA on the Ender 3 V3 SE to validate fit before final use. Printed at 0.20 mm layer height for dimensional accuracy on the mounting holes.',
      tags: ['PLA', 'Own Design', 'Ender 3 V3 SE', 'MGB'],
      model: '/models/washer-adapter.stl',
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Slicer': 'OrcaSlicer',
        'Material': 'PLA',
        'Layer height': '0.20 mm',
        'Design': 'FreeCAD (own)',
      },
      process: [
        'Printed both parts at 0.20 mm for dimensional accuracy on the mounting holes.',
        'Test-fit confirmed hole spacing within 0.3 mm — within bolt clearance tolerance.',
        'Thread engagement checked with M6 bolts; no re-drill required.',
      ],
      images: [],
    },
  },
  {
    id: 'm8-test-plate',
    title: 'M8 Test Plate',
    accent: '#5c4a2a',
    summary: 'Calibration print for dialing in M8 hole diameters on the Ender 3 V3 SE before committing to final designs.',
    cad: {
      cameraPull: 2,
      description: 'Test plate for validating M8 thread fitment and print tolerances before committing to a final design.',
      longDescription:
        "Before finalizing any design that uses M8 hardware, a dedicated test plate was printed to dial in the correct hole diameter for the printer's actual dimensional accuracy. The plate includes multiple M8 holes at slightly different diameters to find the best fit.",
      tags: ['FreeCAD', 'Tolerance Testing'],
      model: '/models/m8-test-plate.stl',
      specs: {
        'Tool': 'FreeCAD',
        'Material': 'PLA',
        'Print time': '2 h 21 min',
        'Printer': 'Ender 3 V3 SE',
        'Purpose': 'M8 tolerance validation',
      },
      process: [
        'Designed a simple flat plate in FreeCAD with a grid of M8 clearance and thread holes at ±0.1 mm tolerance steps.',
        'Printed the full plate and tested M8 bolts and threaded inserts in each hole.',
        'Identified the optimal diameter offset for the Ender 3 V3 SE and applied it to subsequent designs.',
      ],
      images: [],
    },
    printing: {
      cameraPull: 2,
      description: 'Printed the M8 tolerance test plate (~2h 21m print) to validate hole sizing before final part production.',
      longDescription:
        'A calibration print specifically for dialing in M8 hole diameters on the Ender 3 V3 SE. The results from this plate were applied to all subsequent MGB designs that use M8 hardware.',
      tags: ['PLA', 'Own Design', 'Calibration'],
      model: '/models/m8-test-plate.stl',
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Slicer': 'OrcaSlicer',
        'Material': 'PLA',
        'Print time': '2 h 21 min',
        'Purpose': 'M8 tolerance calibration',
      },
      process: [
        'Printed the full test plate in a single run.',
        'Tested M8 bolts in each hole diameter variant — found 8.4 mm nominal gave the best clearance fit on this printer.',
        'Applied the offset to all subsequent FreeCAD models before slicing.',
      ],
      images: [],
    },
  },
]
