export const projects = [
  {
    id: 'ac-bracket',
    title: 'MGB AC Bracket',
    accent: '#1a3a5c',
    summary: 'The MGB was never available from the factory with air conditioning. In a state like Maryland, AC has become a necessity. The goal: design and build a set of brackets that allow a universal AC compressor to be mounted onto the engine.',
    cad: {
      description: 'Custom AC mounting brackets designed in FreeCAD to add air conditioning to a classic car.',
      longDescription:
        'A classic car like the MGB has no factory provision for air conditioning, so there are no off-the-shelf brackets to mount a compressor. A complete set of custom brackets was designed from scratch in FreeCAD to fit the compressor into the engine bay. The parametric models were refined through multiple revisions to clear the engine, accessory drive, and surrounding components.',
      tags: ['FreeCAD', 'Mechanical', 'MGB'],
      model: '/models/ac-bracket-combined.stl',
      modelRotation: [0, 0, Math.PI / 2],
      specs: {
        'Tool': 'FreeCAD',
        'Iterations': '10+',
        'Final Material': 'Metal (fabricated)',
        'Prototype Material': 'PLA',
        'Car': '1980 MGB',
      },
      images: [],
      gallery: [
        { type: 'model', src: '/models/ac-bracket-rev2v4.stl', label: 'Bracket 1' },
        { type: 'model', src: '/models/ac-bracket-rev3.stl', label: 'Bracket 2' },
        { type: 'model', src: '/models/ac-bracket-rev4.stl', label: 'Bracket 3' },
        { type: 'model', src: '/models/ac-bracket-rev5.stl', label: 'Bracket 4' },
        { type: 'model', src: '/models/ac-bracket-rev9.stl', label: 'Bracket 5' },
        { type: 'model', src: '/models/ac-bracket.stl', label: 'Bracket 6' },
        { type: 'model', src: '/models/ac-bracket-rev6.stl', label: 'Bracket 7' },
        { type: 'model', src: '/models/ac-bracket-rev7.stl', label: 'Bracket 8' },
        { type: 'model', src: '/models/ac-bracket1-v3.stl', label: 'Bracket 9' },
      ],
    },
    printing: {
      description: 'Before any metal fabrication, 3D-printed versions of the brackets were tested on the real engine.',
      longDescription:
        'Before committing to metal fabrication, each version of the brackets was 3D printed in PLA and test-fit on the actual engine. Printing inexpensive prototypes made it possible to check the compressor mounting, bolt alignment, and clearances against real hardware — catching fit problems early and feeding the corrections back into the CAD before anything was cut in metal.',
      tags: ['PLA', 'Own Design', 'Ender 3 V3 SE', 'MGB'],
      model: '/models/ac-bracket-combined.stl',
      modelRotation: [0, 0, Math.PI / 2],
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Slicer': 'Cura / OrcaSlicer',
        'Material': 'PLA',
        'Revisions printed': '10+',
        'Design': 'FreeCAD (own)',
      },
      images: [
        '/images/ac-bracket/printing/IMG_8236.jpg',
        '/images/ac-bracket/printing/IMG_8255.jpg',
        '/images/ac-bracket/printing/IMG_8322.jpg',
        '/images/ac-bracket/printing/IMG_8323.jpg',
        '/images/ac-bracket/printing/IMG_8324.jpg',
        '/images/ac-bracket/printing/IMG_8343.jpg',
        '/images/ac-bracket/printing/IMG_8344.jpg',
        '/images/ac-bracket/printing/IMG_8346.jpg',
      ],
      gallery: [
        { type: 'model', src: '/models/ac-bracket-rev2v4.stl', label: 'Bracket 1' },
        { type: 'model', src: '/models/ac-bracket-rev3.stl', label: 'Bracket 2' },
        { type: 'model', src: '/models/ac-bracket-rev4.stl', label: 'Bracket 3' },
        { type: 'model', src: '/models/ac-bracket-rev5.stl', label: 'Bracket 4' },
        { type: 'model', src: '/models/ac-bracket-rev9.stl', label: 'Bracket 5' },
        { type: 'model', src: '/models/ac-bracket.stl', label: 'Bracket 6' },
      ],
    },
    metalwork: {
      description: 'With the CAD designs complete, the drawings were sent to SendCutSend for cutting, then fabricated into the finished brackets.',
      longDescription:
        'Once the CAD designs were finalized and validated with printed prototypes, the bracket drawings were sent out to SendCutSend to be cut from metal. From there, the remaining fabrication was completed — bending, finishing, and hardware — to build up the final assembled brackets.',
      tags: ['Metalwork', 'MGB', 'AC', 'SendCutSend'],
      specs: {
        'Cut by': 'SendCutSend',
        'Source': 'FreeCAD CAD drawings',
        'Car': '1980 MGB',
      },
      images: [
        '/images/ac-bracket/metalwork/IMG_8327.jpg',
        '/images/ac-bracket/metalwork/IMG_8328.jpg',
        '/images/ac-bracket/metalwork/IMG_8379.jpg',
        '/images/ac-bracket/metalwork/IMG_8380.jpg',
        '/images/ac-bracket/metalwork/IMG_8381.jpg',
        '/images/ac-bracket/metalwork/IMG_8382.jpg',
        '/images/ac-bracket/metalwork/IMG_8383.jpg',
        '/images/ac-bracket/metalwork/IMG_8384.jpg',
        '/images/ac-bracket/metalwork/IMG_8385.jpg',
        '/images/ac-bracket/metalwork/IMG_8386.jpg',
        '/images/ac-bracket/metalwork/IMG_8411.jpg',
        '/images/ac-bracket/metalwork/IMG_9576.jpg',
        '/videos/ac-bracket-metal.mp4',
      ],
    },
  },
  {
    id: 'overflow-bottle',
    title: 'MGB Overflow Bottle Bracket',
    accent: '#2a4a6a',
    summary: 'A bracket to adapt a universal coolant overflow bottle to the MGB — replacing the trouble-prone original and relocating it to a roomier spot.',
    cad: {
      cameraPull: 2,
      description: 'Bracket designed in FreeCAD to mount a universal coolant overflow bottle on the MGB and relocate it to a more spacious position.',
      longDescription:
        'The original late-model MGB coolant overflow bottle had ongoing quality issues. Rather than try to fix the original, a well-developed universal bottle was chosen as a replacement. Because the universal bottle mounts differently from the original, a custom bracket was designed in FreeCAD — one that not only adapts the new bottle to the car but also relocates it to a spot in the engine bay with more room.',
      tags: ['FreeCAD', 'Fluid Systems', 'MGB'],
      model: '/models/overflow-bottle.stl',
      specs: {
        'Tool': 'FreeCAD',
        'Revisions': '5',
        'Prototype Material': 'PLA',
        'Car': '1980 MGB',
      },
      images: [],
      gallery: [
        { type: 'model', src: '/models/overflow-bottle.stl', label: 'Overflow bottle bracket' },
      ],
    },
    printing: {
      cameraPull: 2,
      description: 'Printed the overflow bottle bracket on the Ender 3 V3 SE — PLA proved strong and heat-resistant enough to serve as the final part, with no need for metal.',
      longDescription:
        'After 5 FreeCAD design iterations, the overflow bottle bracket was printed in PLA on the Ender 3 V3 SE. Earlier revisions confirmed that the universal bottle sat correctly in its relocated position, with the mounting holes and hose routing all lined up. PLA\'s strength and temperature resistance proved more than enough for this spot in the engine bay, so the printed part is the final bracket — there was no need to fabricate it in metal.',
      tags: ['PLA', 'Own Design', 'Ender 3 V3 SE', 'MGB'],
      model: '/models/overflow-bottle.stl',
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Slicer': 'OrcaSlicer',
        'Material': 'PLA',
        'Design': 'FreeCAD (own)',
      },
      images: [
        '/images/overflow-bottle/printing/IMG_9682.jpg',
        '/images/overflow-bottle/printing/IMG_9683.jpg',
        '/videos/ac-bracket-metal.mp4',
      ],
    },
  },
  {
    id: 'shift-knob',
    title: 'Custom Shift Knob',
    accent: '#3d2a5c',
    summary: 'Ergonomic shift knob for the MGB — curved geometry parametrically modeled in FreeCAD and printed in PLA.',
    cad: {
      cameraPull: 2,
      description: 'Curved shift knob with custom geometry, parametrically modeled and refined across multiple FreeCAD revisions.',
      longDescription:
        'A shift knob designed to fit the MGB gearbox shifter with custom ergonomic geometry. Multiple FreeCAD files track the design evolution — from the base knob shape through curved variants and fillet refinements — until a final printable form was achieved.',
      tags: ['FreeCAD', 'Ergonomic Design'],
      model: '/models/shift-knob.stl',
      specs: {
        'Tool': 'FreeCAD',
        'Design files': 'knob_custom, knob_custom_curved, knob_modify_1, knob_modify_2',
        'Material': 'PLA',
        'Layer height': '0.20 mm',
      },
      images: [],
    },
    printing: {
      cameraPull: 2,
      description: 'Printed the custom shift knob design in PLA; tested curved geometry and fit on the actual shifter.',
      longDescription:
        'The shift knob was printed in PLA across multiple revisions to validate the ergonomic shape and shifter thread fit. Printing at 0.20 mm layer height gave a good surface finish for a hand-contact part while keeping print time reasonable.',
      tags: ['PLA', 'Own Design', 'Ender 3 V3 SE'],
      model: '/models/shift-knob.stl',
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Slicer': 'OrcaSlicer',
        'Material': 'PLA',
        'Layer height': '0.20 mm',
        'Design': 'FreeCAD (own)',
      },
      images: [],
    },
  },
  {
    id: 'washer-system',
    title: 'MGB Washer System',
    accent: '#2a5c4a',
    summary: 'Relocation bracket and adapter for the MGB washer pump — aftermarket components fitted to original mounting points.',
    cad: {
      description: 'Relocation bracket and adapter for the MGB washer pump — designed in FreeCAD to fit aftermarket components to original mounting points.',
      longDescription:
        'Two parts designed together as one system: a relocation bracket to move the washer pump to a new position in the engine bay, and a precision adapter to mate the aftermarket pump body to the original MGB mounting hole pattern. Both were parametrically modeled in FreeCAD so dimensions could be tuned without rebuilding sketches.',
      tags: ['FreeCAD', 'Mechanical', 'MGB'],
      model: '/models/washer-adapter.stl',
      specs: {
        'Tool': 'FreeCAD',
        'Parts': 'Relocation bracket + adapter',
        'Material': 'PLA prototype',
        'Layer height': '0.20 mm',
        'Car': '1980 MGB',
      },
      images: [],
    },
    printing: {
      description: 'Printed the washer relocation bracket and adapter in PLA; validated thread engagement and mounting clearance on both components.',
      longDescription:
        'Both parts of the washer system — the relocation bracket and the adapter — were printed in PLA on the Ender 3 V3 SE to validate fit before final use. Printed at 0.20 mm layer height for dimensional accuracy on the mounting holes.',
      tags: ['PLA', 'Own Design', 'Ender 3 V3 SE', 'MGB'],
      model: '/models/washer-adapter.stl',
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Slicer': 'OrcaSlicer',
        'Material': 'PLA',
        'Layer height': '0.20 mm',
        'Design': 'FreeCAD (own)',
      },
      images: [
        '/images/washer-system/printing/IMG_9681.jpg',
      ],
    },
  },
  {
    id: 'engine-replacement',
    title: 'MGB Engine Replacement',
    accent: '#6a3a2a',
    summary: 'Full engine rebuild and replacement for the 1980 MGB — bare-block teardown, refinish, and reinstall.',
    restoration: {
      description: 'Rebuilt and refinished the MGB four-cylinder engine — from a stripped bare block to a freshly painted unit back in the bay.',
      longDescription:
        'The original MGB engine was pulled and stripped down to the bare block, then cleaned, rebuilt, and refinished before going back into the car. The work spanned the full drivetrain — block, head, accessory drive, and engine-bay wiring — as part of the larger restoration.',
      tags: ['MGB', 'Engine', 'Restoration', 'Mechanical'],
      specs: {
        'Car': '1980 MGB',
        'Scope': 'Bare-block rebuild + reinstall',
        'Finish': 'Repainted block',
      },
      images: [
        '/images/engine-replacement/IMG_8360.jpg',
        '/images/engine-replacement/IMG_9016.jpg',
        '/images/engine-replacement/IMG_9227.jpg',
        '/images/engine-replacement/IMG_9278.jpg',
        '/images/engine-replacement/IMG_9339.jpg',
        '/images/engine-replacement/IMG_9367.jpg',
        '/images/engine-replacement/IMG_9370.jpg',
        '/images/engine-replacement/IMG_9372.jpg',
        '/images/engine-replacement/IMG_9392.jpg',
        '/images/engine-replacement/IMG_9393.jpg',
        '/images/engine-replacement/IMG_9396.jpg',
        '/images/engine-replacement/IMG_9397.jpg',
        '/images/engine-replacement/IMG_9476.jpg',
        '/images/engine-replacement/IMG_9477.jpg',
        '/images/engine-replacement/IMG_9479.jpg',
        '/images/engine-replacement/IMG_9496.jpg',
        '/images/engine-replacement/IMG_9529.jpg',
      ],
    },
  },
  {
    id: 'mgb-speedometer',
    title: 'MGB Speedometer',
    accent: '#4a4a2a',
    summary: 'Refurbishing the original MGB speedometer and designing replacement gears and housing in CAD.',
    cad: {
      description: 'Designed replacement speedometer internals in FreeCAD — the gear train and housing for the MGB speedometer.',
      longDescription:
        'Modeled the speedometer drive gears and housing in FreeCAD, iterating on tooth counts and fit. The gear set (20- and 25-tooth involute gears) was developed alongside several revisions of the speedometer body, with test prints used to check meshing and bearing fit before finalizing.',
      tags: ['FreeCAD', 'Involute Gears', 'MGB', 'Mechanical'],
      model: '/models/speedo-gear-20t.stl',
      specs: {
        'Tool': 'FreeCAD',
        'Components': 'Gear train + housing',
        'Gears': '20t / 25t',
        'Car': '1980 MGB',
      },
      images: [],
      gallery: [
        { type: 'model', src: '/models/speedo-gear-20t.stl', label: '20-tooth gear' },
        { type: 'model', src: '/models/speedo-gear-25t.stl', label: '25-tooth gear' },
        { type: 'model', src: '/models/speedo-gears-together.stl', label: 'Gears assembled', rotation: [-Math.PI / 2, 0, 0] },
      ],
    },
    restoration: {
      description: 'Cleaned up and serviced the original MGB speedometer head as part of restoring the instrument cluster.',
      longDescription:
        'The original speedometer was removed and serviced as part of bringing the MGB instrument cluster back to working condition — checking the mechanism and odometer before refitting to the dash.',
      tags: ['MGB', 'Instruments', 'Restoration'],
      specs: {
        'Car': '1980 MGB',
        'Component': 'Speedometer head',
      },
      images: [
        '/images/mgb-speedometer/IMG_9608.jpg',
        '/images/mgb-speedometer/IMG_9609.jpg',
        '/images/mgb-speedometer/IMG_9610.jpg',
        '/images/mgb-speedometer/IMG_9611.jpg',
      ],
    },
  },
  {
    id: 'mgb-vintage',
    title: 'Vintage MGB Restoration',
    accent: '#5c2a2a',
    summary: 'Archive photos from the original MGB restoration — bodywork, bare shell, and the rebuilt car.',
    restoration: {
      description: 'Scanned archive photos documenting the original MGB restoration, from a stripped shell through the finished car.',
      longDescription:
        'A set of scanned film photos from the earlier MGB restoration — the stripped and primed body shell, engine bay, interior, and the finished car at a show. These document the first round of work that the current project builds on.',
      tags: ['MGB', 'Restoration', 'Archive'],
      images: [
        '/images/mgb-vintage/Photo651774476995_inner_41-156-686-152-41-832-709-824.jpg',
        '/images/mgb-vintage/Photo651774543175_inner_114-164-612-172-149-891-630-867.jpg',
        '/images/mgb-vintage/Photo651774634144_inner_79-176-519-176-88-797-521-781.jpg',
        '/images/mgb-vintage/Photo651774645174_inner_85-207-545-207-114-875-574-840.jpg',
        '/images/mgb-vintage/Photo651774755290_inner_41-66-624-105-38-926-609-898.jpg',
        '/images/mgb-vintage/Photo651774774126_inner_91-86-665-121-105-953-665-918.jpg',
        '/images/mgb-vintage/Photo651774810310_inner_103-98-618-90-103-836-647-836.jpg',
        '/images/mgb-vintage/Photo651774841810_inner_97-133-562-129-111-801-586-781.jpg',
        '/images/mgb-vintage/Photo651774876528_inner_135-156-618-164-144-867-618-836.jpg',
        '/images/mgb-vintage/Photo651774894330_inner_85-152-601-164-85-867-583-848.jpg',
      ],
    },
  },
  {
    id: 'treehouse',
    title: 'Backyard Treehouse',
    accent: '#3a5c2a',
    summary: 'A two-level backyard treehouse built from the ground up — framing, walls, roof, and paint.',
    woodworking: {
      description: 'Designed and built a backyard treehouse around a standing tree — platform, framed walls, roof, ladder, and a painted finish.',
      longDescription:
        'A from-scratch treehouse build: a load-bearing platform anchored around the tree, framed plywood walls with cut-out windows, a pitched roof, an access ladder, and a painted exterior. Built over a series of weekends and documented from the first platform beams through the finished, weathered structure years later.',
      tags: ['Woodworking', 'Carpentry', 'Outdoor Build'],
      specs: {
        'Structure': 'Two-level platform + enclosed house',
        'Materials': 'Pressure-treated lumber, plywood',
        'Finish': 'Exterior paint',
      },
      images: [
        '/images/treehouse/20170408_142254.jpg',
        '/images/treehouse/20170408_173428.jpg',
        '/images/treehouse/20170408_173441.jpg',
        '/images/treehouse/20170409_145201.jpg',
        '/images/treehouse/20170409_145214.jpg',
        '/images/treehouse/20170418_154430.jpg',
        '/images/treehouse/20170418_154458.jpg',
        '/images/treehouse/20170418_154720.jpg',
        '/images/treehouse/20170502_153259.jpg',
        '/images/treehouse/20170516_103108.jpg',
        '/images/treehouse/20170516_113652.jpg',
        '/images/treehouse/20170516_120354.jpg',
        '/images/treehouse/20170516_122412.jpg',
        '/images/treehouse/20170516_122424.jpg',
        '/images/treehouse/20170516_190237.jpg',
        '/images/treehouse/20170608_190031.jpg',
        '/images/treehouse/20170608_190043.jpg',
        '/images/treehouse/20210904_080652.jpg',
        '/images/treehouse/FB_IMG_1491843605982.jpg',
        '/images/treehouse/IMG_20170904_182050.jpg',
        '/images/treehouse/IMG_20170904_182107.jpg',
        '/images/treehouse/IMG_20170904_190405.jpg',
      ],
    },
  },
  {
    id: 'expansion-card-box',
    title: 'Retro Computer Enclosures',
    accent: '#2a4a5c',
    summary: '3D-printed cases and stands for retro-computing hardware, printed on the Ender 3 V3 SE.',
    printing: {
      description: '3D-printed enclosures and stands for retro-computing projects — including a case for an expansion-card adapter board.',
      longDescription:
        'A set of 3D-printed parts for retro-computing hardware: a snap-together case for a small expansion-card adapter board and a printed stand for an old machine. Printed in PLA on the Ender 3 V3 SE and sized to the boards they hold.',
      tags: ['PLA', 'Ender 3 V3 SE', 'Enclosure', 'Retro Computing'],
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Material': 'PLA',
        'Slicer': 'OrcaSlicer',
      },
      images: [
        '/images/expansion-card-box/IMG_9457.jpg',
        '/images/expansion-card-box/IMG_9460.jpg',
        '/images/expansion-card-box/IMG_9461.jpg',
      ],
    },
  },
  {
    id: 'headphone-mod',
    title: 'Headphone Mod',
    accent: '#3d2a4a',
    summary: '3D-printed parts to modify and repair a pair of headphones.',
    printing: {
      description: '3D-printed replacement parts to modify and repair a pair of over-ear headphones.',
      longDescription:
        'Custom 3D-printed components to repair and modify a pair of over-ear headphones — printed in PLA on the Ender 3 V3 SE and fitted to the existing earcups and hardware.',
      tags: ['PLA', 'Ender 3 V3 SE', 'Repair', 'Audio'],
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Material': 'PLA',
      },
      images: [
        '/images/headphone-mod/IMG_8493.jpg',
        '/images/headphone-mod/IMG_8494.jpg',
        '/images/headphone-mod/IMG_8495.jpg',
        '/images/headphone-mod/IMG_8496.jpg',
      ],
    },
  },
  {
    id: 'smiley-paddle',
    title: 'Smiley Paddle',
    accent: '#5c2a4a',
    summary: 'A one-off 3D-printed paddle with an embossed smiley and engraved text.',
    printing: {
      description: 'A one-off 3D-printed paddle printed in red PLA, with an embossed smiley face and engraved lettering.',
      longDescription:
        'A novelty 3D-printed paddle with an embossed smiley and engraved text, printed in red PLA on the Ender 3 V3 SE. A quick one-off print to try out embossed/engraved surface detail.',
      tags: ['PLA', 'Ender 3 V3 SE', 'One-off'],
      specs: {
        'Printer': 'Ender 3 V3 SE',
        'Material': 'PLA',
        'Color': 'Red',
      },
      images: [
        '/images/smiley-paddle/IMG_8455.jpg',
        '/images/smiley-paddle/IMG_8458.jpg',
      ],
    },
  },
]
